### ISSUE TITLE
Unable to install tstoolbox 103.9.8

### ISSUE THREAD

**Issue by japageth** [timcera/tstoolbox#5]
Version 103.9.8 of the tstoolbox package depends on plottoolbox, which is a package that I couldn't find either in pypi or your GitHub site or by searching Google.  As a result, pip installs Version 103.8.8, which lacks this dependency.

**Commands to install tstoolbox and help with troubleshooting:**
`pip uninstall tstoolbox`
`pip install --no-cache-dir "tstoolbox==103.9.8"`

**A bit about my setup:**
Windows Professional 64-bit Version 20H2
Python 3.9.6 (64-bit)
pip version: 21.1.3
Packages are installed directly from pypi or [Christophe Gohlke's site](https://www.lfd.uci.edu/~gohlke/pythonlibs).
I install the latest version of all packages unless there is a problem or a dependency conflict with the latest version.

**Comment by timcera** [comment]
Thank you.  Had some problems getting plottoolbox rolled out and forgot that I had made it a dependency of tstoolbox.

Probably be fixed this weekend and posted to pypi.

Kind regards,
Tim

**Comment by timcera** [comment]
This is fixed now.  I just had to roll out plottoolbox.  Apologies that I didn't get back to you right away.
